// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3Zw-CAnW0VFQR0ipQFfn58w0eqWfdP0',
    appId: '1:636552914502:web:c0625c78c473bea08a8c47',
    messagingSenderId: '636552914502',
    projectId: 'ecommerce-t-2003',
    authDomain: 'ecommerce-t-2003.firebaseapp.com',
    storageBucket: 'ecommerce-t-2003.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClEYvPblfo7r_paGgsUdSYU8SPTm1xqoQ',
    appId: '1:934236600317:android:31da1d5498b3d6d0484b94',
    messagingSenderId: '934236600317',
    projectId: 'wink-e51d9',
    storageBucket: 'wink-e51d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO-10Pp4ur-vuwE9Hem3cJYiImcOkMZAA',
    appId: '1:772445374177:ios:1ecc56d1d7692ed7f3d9a0',
    messagingSenderId: '772445374177',
    projectId: 'wink-e636d',
    storageBucket: 'wink-e51d9.firebasestorage.app',
    iosBundleId: 'com.brafacorp.wink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx7rVg9870AGCbDfzMR_-KUavCQlPDf64',
    appId: '1:636552914502:ios:0dfaf922c9dbc87e8a8c47',
    messagingSenderId: '636552914502',
    projectId: 'ecommerce-t-2003',
    storageBucket: 'ecommerce-t-2003.appspot.com',
    iosBundleId: 'com.exabrafacorpmple.wink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN3Zw-CAnW0VFQR0ipQFfn58w0eqWfdP0',
    appId: '1:636552914502:web:599c1f91593b79188a8c47',
    messagingSenderId: '636552914502',
    projectId: 'ecommerce-t-2003',
    authDomain: 'ecommerce-t-2003.firebaseapp.com',
    storageBucket: 'ecommerce-t-2003.appspot.com',
  );

}