name: Build iOS IPA

on:
  workflow_dispatch: # Esto permite ejecutarlo manualmente desde GitHub Actions

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # pon tu versión actual de Flutter

      - name: Enable iOS
        run: flutter config --enable-ios

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA (no firmado)
        run: flutter build ios --no-codesign

      - name: Create unsigned IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: app.ipa
