name: Build iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Enable iOS support
        run: flutter config --enable-ios

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS app (no code signing)
        run: flutter build ios --no-codesign --release

      - name: Package unsigned IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-unsigned-ipa
          path: app.ipa
